version: "3.4"
services:
  maple-vuetify:
    image: node:alpine
    container_name: maple-vuetify
    entrypoint: /bin/sh
    ports:
      - 9056:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./vue-app
        target: /srv/app
    tty: true
